config/routes.rb
Rails.application.routes.draw do

  get 'bookings/index'

  get 'bookings/client_bookings'

  get 'bookings/show'

  get 'bookings/edit'

  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations',
                               :sessions => 'users/sessions'
  														}

  devise_for :administrators,
             path: '',
             path_names: {sign_in: 'admin_login', sign_out: "admin_logout"},
             controllers: {sessions: "administrators/sessions"}

  resources :users, only: [:show]
  resources :rooms
  resources :photos
  resources :experiences
  resources :expphotos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :actphotos
  resources :activities

  resources :experiences do 
    resources :expreservations, only: [:create]
    resources :activities
  end

  resources :professionals, only: [:index, :show] do
    post 'submit_application', on: :member
    get 'apply', on: :collection
  end

  resources :services, only: [:index, :show] do
    post :book, on: :member
  end

  get '/my_services' => 'services#my_services'

  resources :my_services, controller: "services", only: [:new, :edit, :create, :update, :destroy]


  resources :my_bookings, controller: "bookings", only: [:index, :show, :edit]

  get '/client_bookings' => 'bookings#client_bookings'
  get '/client_bookings/:id', to: "bookings#show_client", as: "show_client_booking"

  namespace :administration do
    get "dashboard", to: "dashboard#index", as: "dashboard"
    resources :professionals, only: [:index] do
      get "for_approval", on: :collection
      patch "approve", on: :member
    end
    resources :service_categories, only: [:index, :new, :create, :edit, :update, :delete]
    resources :services, only: [:index, :show] do
      patch "status_update", on: :member      
    end
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/exp_your_itineraries' => 'expreservations#exp_your_itineraries'

  post '/exp_notify' => 'expreservations#exp_notify'
  post '/exp_your_itineraries' => 'expreservations#exp_your_itineraries'
  

  get '/search' => 'pages#search'
  get '/homes' => 'pages#homes'

end

app/models/service.rb
module Service
  def self.table_name_prefix
    'service_'
  end
end

app/models/service/booking.rb
class Service::Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :service, class_name: "Service::Service", foreign_key: :service_service_id
  has_one :professional, class_name: "Professional::User", foreign_key: :professional_user_id
  has_one :address, as: :addressable
  has_one :payment, as: :payable
  has_many :my_answers, class_name: "Service::MyAnswer", foreign_key: :service_booking_id

  accepts_nested_attributes_for :address, reject_if: :all_blank, allow_destroy: true  
  accepts_nested_attributes_for :my_answers, reject_if: :all_blank, allow_destroy: true  

  # validates_presence_of :address, if: :visit?
  validates :date,
  					presence: true,
  					uniqueness: {
  						scope: :professional_user_id
  					}

  def self.statuses
  	[
  		'pending',
  		'approved',
  		'moved',
  		'cancelled'
  	]
  end

  def status_readable
  	Service::Booking.statuses[self.status]
  end

  def payment_status
  	payment.status
  end

  def payment_status_readable
  	payment.status_readable
  end

  before_create :set_price
  before_create :set_create_status

  private
  def set_price
  	if service.discounted_rate.present?
  		self.price = service.discounted_rate
  	else
  		self.price = service.rate
    end
  end

  def set_create_status
    self.status = 0
  end
end

app/models/service/category.rb
class Service::Category < ActiveRecord::Base
	has_many :services, foreign_key: :service_category_id, class_name: "Service::Service"
	has_many :questions, as: :questionable
	has_many :answers, through: :questions
	has_many :professionals, through: :services

	accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :answers,  reject_if: :all_blank, allow_destroy: true

	validates :title, :description, :minimum_rate, :maximum_rate, presence: true
	validates :commission_percentage,
						presence: true,
						numericality: {
							less_than_or_equal_to: 100
						}
	validates :slug,
						uniqueness: true

	before_validation :set_slug

	def to_param
		self.slug
	end

	private
	def set_slug
		if slug.blank?
			self.slug = title.parameterize
		else
			self.slug = slug.parameterize
		end
	end
end

app/models/service/my_answer.rb
class Service::MyAnswer < ActiveRecord::Base
  belongs_to :booking, class_name: "Service::Booking", foreign_key: :service_booking_id
  belongs_to :answer
  has_one :user, through: :booking
  has_one :service, through: :booking
  has_one :question, through: :answer
  has_one :professional, through: :service

  validates :answer_id, presence: true
  validates_uniqueness_of :answer_id, scope: :service_booking_id
end

app/models/service/service.rb
class Service::Service < ActiveRecord::Base
  belongs_to :professional, class_name: "Professional::User", foreign_key: :professional_id
  belongs_to :service_category, class_name: "Service::Category", foreign_key: :service_category_id
  has_many :bookings, class_name: "Service::Booking", foreign_key: :service_service_id
  has_many :bookees, through: :bookings
  has_many :questions, through: :service_category
  has_many :images, as: :imageable
  has_one :address, as: :addressable

  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :address, reject_if: :all_blank, allow_destroy: true

  scope :approved, lambda {where(status: 1)}
  scope :pending, lambda {where(status: 0)}

  validates :rate,
  					numericality: {
  						less_than_or_equal_to: :maximum_rate,
  						greater_than_or_equal_to: :minimum_rate
  					}
  validates :description,
  					presence: true,
  					length: {
  						minimum: 255,
  						maximum: 2000
  					}
  validates :title,
  					presence: true,
  					length: {
  						minimum: 10,
  						maximum: 500
  					}
  validates :discounted_rate,
            allow_nil: true,
            allow_blank: true,
  					numericality: {
  						less_than_or_equal_to: :rate
  					}

  def self.statuses
  	[
  		'pending',
  		'approved',
  		'cancelled',
  		'revision'
  	]
  end

  def status_readable
  	Service::Service.statuses[self.status]
  end

  def maximum_rate
  	service_category.maximum_rate
  end

  def minimum_rate
  	service_category.minimum_rate
  end

  def visit?
  	address.area?
  end

  def discounted?
    self.discounted_rate.present?
  end

  def approved?
    self.status == 1
  end

  def category
    self.service_category.title
  end
end

app/controllers/administration/services_controller.rb
class Administration::ServicesController < AdministrationController
	before_action :set_service, only: [:status_update, :show]

  def index
  	@services = Service::Service.all
  end

  def status_update
  	if @service.update_attributes(status_update_params)
  		redirect_to administration_services_path, notice: "Successfully updated status of service."
  	else
  		render "index"
  	end
  end

  def show

  end

  private
  def set_service
  	@service = Service::Service.find(params[:id])
  end

  def status_update_params
  	params.require(:service_service).permit(:status)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

	before_action :set_service, only: [:show, :edit, :update, :destroy, :book, :review]
	before_action :validate_service_ownership, only: [:edit, :update, :destroy, :review]
	before_action :is_user_professional, only: [:my_services, :new, :create, :review, :edit, :update, :destroy]

  def index
  	@services = Service::Service.approved
  end

  def my_services
  	@services = current_user.services
  end

  def show
    @booking = @service.bookings.build

    @service.questions.each do |q|
      @booking.my_answers.build(question: q)
    end

    if @service.visit?
      @booking.build_address
    end
  end

  def new
  	@service = current_user.services.build
    @service.build_address
  end

  def create
  	@service = Service::Service.new(service_params)
  	if @service.save
  		redirect_to edit_my_service_path(@service), notice: "Successfully created a service."
  	else
  		render "new"
  	end
  end

  def review
  end

  def edit
    if !@service.address.present?
      @service.build_address
    end
  end

  def update
  	if @service.update_attributes(service_params)
  		redirect_to edit_my_service_path(@service), notice: "Successfully updated a service."
  	else
  		render "edit"
  	end
  end

  def destroy
  	@service.destroy
  	redirect_to my_services_path, notice: "Successfully destroyed service."
  end

  def book
    @booking = Service::Booking.new(booking_params)
    if @booking.save
      redirect_to service_path(params[:id]), notice: "Your booking request has been submitted. It will be reviewed by the professional and will get back to you."
    else
      render "show"
    end
  end

  private
  def set_service
  	@service = Service::Service.find(params[:id])
  end

  def service_params
  	params.require(:service_service).permit(:title, :description, :rate, :discounted_rate, :service_category_id, :professional_id,
      address_attributes: [
        :id, :address_type, :first_line, :second_line, :city, :state, :country, :zip_code
      ],
  		images_attributes: [
  			:id, :_destroy, :img, :description
  		]
  	)
  end

  def booking_params
    params.require(:service_booking).permit(:user_id, :professional_user_id, :date, :notes, :service_service_id,
      my_answers_attributes: [
        :answer_id, :service_booking_id
      ],
      address_attributes: [
        :first_line, :second_line, :city, :state, :country, :address_type
      ]
    )
  end

  def validate_service_ownership
  	if @service.professional != current_user
  		redirect_to services_path, notice: "You do not own this service."
  	end
  end
end

app/helpers/administration/services_helper.rb
module Administration::ServicesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for @service, url: url, method: method do |f| %>
	<%= f.input :professional_id, as: :hidden, input_html: {value: current_user.id} %>
	<%= f.input :title, as: :string %>
	<%= f.association :service_category, as: :select, include_blank: false %>
	<%= f.input :description %>
	<%= f.input :rate %>
	<%= f.input :discounted_rate %>
	<h4>Service Address</h4>
	<%= f.simple_fields_for :address do |add| %>
		<%= add.input :address_type, as: :select, collection: Address.address_types.each_with_index.map{|t, i| [t, i]}, include_blank: false %>
		<p><i>Selecting area will not require filling out the First Line</i></p>
		<div class="row">
			<div class="col-sm-12 col-md-6">
				<%= add.input :first_line, as: :string %>
			</div>
			<div class="col-sm-12 col-md-6">
				<%= add.input :second_line, as: :string %>
			</div>
			<div class="col-sm-6 col-md-3">
				<%= add.input :city %>
			</div>
			<div class="col-sm-6 col-md-3">
				<%= add.input :state %>
			</div>
			<div class="col-sm-6 col-md-3">
				<%= add.input :country, include_blank: false %>
			</div>
			<div class="col-sm-6 col-md-3">
				<%= add.input :postal_code %>
			</div>
		</div>
	<% end %>
	<h4>Images</h4>
	<div id="images" class="row">
		<%= f.simple_fields_for :images do |img| %>
			<%= render "image_fields", f: img %>
		<% end %>
		<div class="links col-sm-12">
			<%= link_to_add_association "Add Image", f, :images, class: "btn btn-warning" %>
		</div>
	</div>
	<div class="row">
		<div class="col xs-12">
			<%= f.submit class: "btn btn-lg btn-success" %>
		</div>		
	</div>
<% end %>

app/views/services/_image_fields.html.erb
<div class="nested-fields col-sm-12 col-md-6 col-lg-4">
	<% if f.object.img.present? %>
		<%= image_tag f.object.img.url(:s_thumb) %>
	<% end %>
	<%= f.input :img %>
	<%= f.input :description %>
	<%= link_to_remove_association "Remove Image", f, class: "btn btn-danger" %>
<hr>
</div>

app/views/services/edit.html.erb
<div class="container">
	<h2>Editing: <%= @service.title %></h2>
	<%= render 'form', url: my_service_path(@service), method: :patch %>
</div>

app/views/services/index.html.erb
<div class="container">
	<h1>Services</h1>
	
	<div class="row">
	
	<% @services.each do |service| %>
			<div class="col-sm-12 col-md-4">
				<% if service.images.present? %>
					<%= image_tag service.images.first.img.url(:m_thumb) %>
				<% end %>
				<h3><%= service.title %></h3>
				<h5><i><%= service.category %></i></h5>
				<p class="lead"><%= service.professional.fullname %></p>
				<p class="lead"><%= number_to_currency service.rate %></p>
				<p><%= service.address.address_type_readable.titleize %>: <%= service.address.display_address %></p>
				<p><%= truncate service.description, length: 255 %></p>
				<%= link_to "View", service_path(service), class: "btn btn-primary" %>
			</div>
	<% end %>

	</div>
</div>

app/views/services/my_services.html.erb
<div class="container">
	<h1>My Services</h1>
	<%= link_to "Create New Service", new_my_service_path, class: "btn btn-lg btn-primary" %>

	<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Category</th>
			<th>Rate</th>
			<th>Discounted Rate</th>
			<th>Status</th>
			<th colspan="1"></th>
		</tr>
	</thead>
	<tbody>
		<% @services.each do |service| %>
			<tr>
				<td><%= service.id %></td>
				<td><%= service.title %></td>
				<td><%= service.service_category.title %></td>
				<td><%= number_to_currency service.rate %></td>
				<td><%= number_to_currency service.discounted_rate %></td>
				<td><%= service.status_readable %></td>
				<td>
					<%= link_to "Edit", edit_my_service_path(service), class: "btn btn-xs btn-warning" %>
					<%= link_to "Review", "#", class: "btn btn-xs btn-warning" %>
					<%= link_to "Delete", my_service_path(service), method: :delete, data: {confirm: "are you sure you want to delete this service?"}, class: "btn btn-xs btn-danger" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/services/new.html.erb
<div class="container">
	<h2>New Service</h2>
	<%= render 'form', url: my_services_path, method: :post %>
</div>

app/views/services/show.html.erb
<div class="container">
	<h1><%= @service.title %></h1>
	<h3><%= @service.professional.fullname %></h3>
	<div class="row">
		<div class="col-sm-12 col-md-8">
			<% if @service.images.present? %>
				<%= render "shared/bootstrap_slider", images_collection: @service.images %>
			<% end %>
			<h3><%= @service.category %></h3>
			<p class="lead">
				<%= @service.address.display_address %>
				<br>
				<i><%= @service.address.address_type_readable %></i>
			</p>
			
			<hr>
			<p><%= @service.description %></p>
		</div>
		<div class="col-sm-12 col-md-4">
			<h3><%= number_to_currency @service.rate %></h3>
			<br>
			<% if user_signed_in? %>
				<% if current_user != @service.professional %>
					<h4>Book Now</h4>
					<%= simple_form_for @booking, url: book_service_path(@service), method: :post do |f| %>
						<%= f.input :professional_user_id, as: :hidden, input_html: {value: @service.professional.id} %>
						<%= f.input :user_id, as: :hidden, input_html: {value: current_user.id} %>
						<%= f.input :service_service_id, as: :hidden, input_html: {value: @service.id} %>

						<%= f.simple_fields_for :my_answers do |fa| %>
							<%= fa.object.question.question %>
							<%= fa.association :answer, as: :select, collection: fa.object.question.answers, label: false, label_method: :answer, include_blank: false %>
						<% end %>
						
						<hr>
						<h5>Booking details</h5>
						<%= f.simple_fields_for :address do |add| %>
							<%= add.input :address_type, as: :hidden, input_html: {value: 1} %>
							<%= add.input :first_line, as: :string %>
							<%= add.input :second_line, as: :string %>
							<%= add.input :city %>
							<%= add.input :state %>
							<%= add.input :country, include_blank: false %>
						<% end %>

						<%= f.input :date, as: :datetime %>
						<%= f.input :notes, label: "Additional booking notes" %>
						
						<%= f.submit class: "btn btn-primary btn-lg" %>
					<% end %>
				<% else %>
					<h5>You are vieweing your own service.</h5>
				<% end %>
			<% else %>
				<h5>You must <%= link_to "login", new_user_session_path %> to book a service.</h5>
			<% end %>
		</div>
	</div>
</div>