config/routes.rb
Rails.application.routes.draw do

  get 'bookings/index'

  get 'bookings/client_bookings'

  get 'bookings/show'

  get 'bookings/edit'

  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations',
                               :sessions => 'users/sessions'
  														}

  devise_for :administrators,
             path: '',
             path_names: {sign_in: 'admin_login', sign_out: "admin_logout"},
             controllers: {sessions: "administrators/sessions"}

  resources :users, only: [:show]
  resources :rooms
  resources :photos
  resources :experiences
  resources :expphotos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :actphotos
  resources :activities

  resources :experiences do 
    resources :expreservations, only: [:create]
    resources :activities
  end

  resources :professionals, only: [:index, :show] do
    post 'submit_application', on: :member
    get 'apply', on: :collection
  end

  resources :services, only: [:index, :show] do
    post :book, on: :member
  end

  get '/my_services' => 'services#my_services'

  resources :my_services, controller: "services", only: [:new, :edit, :create, :update, :destroy]


  resources :my_bookings, controller: "bookings", only: [:index, :show, :edit]

  get '/client_bookings' => 'bookings#client_bookings'
  get '/client_bookings/:id', to: "bookings#show_client", as: "show_client_booking"

  namespace :administration do
    get "dashboard", to: "dashboard#index", as: "dashboard"
    resources :professionals, only: [:index] do
      get "for_approval", on: :collection
      patch "approve", on: :member
    end
    resources :service_categories, only: [:index, :new, :create, :edit, :update, :delete]
    resources :services, only: [:index, :show] do
      patch "status_update", on: :member      
    end
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/exp_your_itineraries' => 'expreservations#exp_your_itineraries'

  post '/exp_notify' => 'expreservations#exp_notify'
  post '/exp_your_itineraries' => 'expreservations#exp_your_itineraries'
  

  get '/search' => 'pages#search'
  get '/homes' => 'pages#homes'

end

app/views/shared/_bootstrap_slider.html.erb
<!-- slider for images -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
  	<% images_collection.each_with_index do |img, i| %>
    <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="<%= "active" if i == 0 %>"></li>
  	<% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  	<% images_collection.each_with_index do |img, i| %>
			<div class="item <%= "active" if i == 0 %>">
				<%= image_tag img.img.url(:large) %>
				<div class="carousel-caption">
					<%= img.description %>
				</div>
			</div>
  	<% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- end sliders -->

app/views/shared/_devisemes.html.erb
<% new_user = User.new %>

<% unless new_user.errors.empty? %>
	<script type="text/javascript">
		<% new_user.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_modal_login.html.erb
    <div class="modal fade" id="modal-gohiso-login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">

                  <div id="gh-login-form">
   

                      <%= link_to "<i class=\"fa fa-facebook pull-left\"></i> Sign in with Facebook".html_safe, user_facebook_omniauth_authorize_path, class: "btn btn-block btn-lg btn-bordered btn-facebook" %>
                      
                      <%= link_to "<i class=\"fa fa-google pull-left\"></i> Sign In with Google".html_safe, user_google_oauth2_omniauth_authorize_path, class: "btn btn-block btn-lg btn-bordered btn-google" %>

                        <div class="signup-or-separator">
                            <span class="h6 signup-or-separator--text">OR</span>
                            <hr>
                        </div>
                        <br />

                      <% new_user = User.new %>
                      <%= form_for(new_user, as: :user, url: session_path(:user)) do |f| %>
                        <%= render 'shared/devisemes', user: new_user %>

                          <div class="form-group">
                            <%= f.email_field :email, autofocus: true, :class => "form-control", :placeholder => "Email" %>
                          </div>

                          <div class="form-group">
                            <%= f.password_field :password, autocomplete: "off", :class => "form-control", :placeholder => "Password" %>
                          </div>

                          <%# if Devise.mappings[:user].rememberable? %>
                            <div class="form-group">
                              <span class="pull-left"><%= f.check_box :remember_me %> Remember Me</span>
                              <span class="pull-right">
                              <%= link_to "Forgot Password", new_user_password_path, :class => "link-forgot" %>
                              </span>
                              <br class="clear" />
                            </div>
                          <%# end %>

                          <div class="actions text-center">
                            <%= f.submit "LOG IN", :class => "btn btn-primary btn-block" %>
                          </div>

                      <% end %>


                  </div>


                </div>


            </div>
        </div>
    </div>

app/views/shared/_modal_signup.html.erb
    <div class="modal fade" id="modal-gohiso-signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">

                  <div id="gh-signup-form">

                      <%= link_to "<i class=\"fa fa-facebook pull-left\"></i> Sign Up with Facebook".html_safe, user_facebook_omniauth_authorize_path, class: "btn btn-block btn-lg btn-bordered btn-facebook" %>
                      
                      <%= link_to "<i class=\"fa fa-google pull-left\"></i> Sign Up with Google".html_safe, user_google_oauth2_omniauth_authorize_path, class: "btn btn-block btn-lg btn-bordered btn-google" %>

                        <div class="signup-or-separator">
                            <span class="h6 signup-or-separator--text">OR</span>
                            <hr>
                        </div>
                        <br />

                      <% new_user = User.new %>
                      <%= form_for(new_user, as: :user, url: registration_path(:user)) do |f| %>                        <%= render 'shared/devisemes', user: new_user %>

                          <div class="form-group">
                            <%= f.text_field :fullname, :class => 'form-control', :placeholder => 'Full Name', autofocus: true %>
                          </div>

                          <div class="form-group">
                            <%= f.email_field :email, autofocus: true, :class => "form-control", :placeholder => "Email" %>
                          </div>

                          <div class="form-group">
                            <% if @validatable %>
                              <em>(<%= @minimum_password_length %> characters minimum)</em>
                            <% end %>
                            <%= f.password_field :password, :class => 'form-control', :placeholder => 'Password', autocomplete: "off" %>
                          </div>

                          <div class="actions text-center">
                            <%= f.submit "SIGN UP", :class => "btn btn-primary btn-block" %>
                          </div>

                      <% end %>


                  </div>


                </div>


            </div>
        </div>
    </div>

app/views/shared/_navbar.html.erb
<% unless current_page?(root_path) %>
  <div class="hero-header-noimage"> 
<% else %>
  <div class="hero-header-navwrap" style="background-image: url('/assets/sample-banner-stockinger.jpg')">
<% end %>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top nav-gradient">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
               <img src="/assets/logo-gohiso.jpg" alt="GoHiSo" height="40" />
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
            </div>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            
            <% if !user_signed_in? && !administrator_signed_in? %>

              <li>
                 <a href="#modal-gohiso-login" data-toggle="modal" data-target="#modal-gohiso-login">
                  Log in
                 </a>
              </li>
              <li><a href="#modal-gohiso-signup" data-toggle="modal" data-target="#modal-gohiso-signup">
                  Sign Up
                 </a></li>
            <% elsif user_signed_in? %>
              
              <% if current_user.user_level != 0 || nil %>
                <li class="hilite">
                  <%= link_to "New Service", new_my_service_path %>
                </li>
              <% else %>
                <li class="hilite">
                  <%= link_to "Become a Professional", apply_professionals_path %>
                </li>
              <% end %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag avatar_url(current_user), class: "img-circle avatar-small", alt: "?" %>&nbsp;
                  <%= current_user.fullname %> <span class="caret"></span>
                </a>

                <ul class="dropdown-menu">
                  <% if current_user.professional? %>
                    <li><%= link_to "My Services", my_services_path %></li>
                    <li><%= link_to "Client Bookings", client_bookings_path %></li>
                  <% end %>
                  <li><%= link_to "My Bookings", my_bookings_path %></li>
                  <li><%= link_to "Your Listings", rooms_path %></li>
                  <li><%= link_to "Your Reservations", your_reservations_path %></li>
                  <li><%= link_to "Your Trips", your_trips_path %></li>
                  <li><a href="exp_your_itineraries">Your Itineraries</a></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Account Setting</a></li>
                  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% elsif administrator_signed_in? %>
              <li class="hilite">
                <%= link_to "Administration", administration_dashboard_path %>
              </li>
              <li>
                <%= link_to "Log Out", destroy_administrator_session_path, method: :delete %>
              </li>
            <% end %>

            <li>
              <%= link_to conversations_path do %>
                Messages
              <% end %>
            </li>


            
          </ul>
          
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <% if current_page?(root_path) %>
    <div class="container">
        <div class="text-desc">
            <h2>Marlon Stockinger</h2>
            <p>Nonumy postea malorum ex pro, ne luptatum accommodare vis. Ex vim illum lorem, ad est suas mediocritatem.</p>
            <div class="rating-stars">
                <i class='fa fa-star'></i>
                <i class='fa fa-star'></i>
                <i class='fa fa-star'></i>
                <i class='fa fa-star'></i>
                <i class='fa fa-star-o'></i>
            </div>
        </div>
    </div>

    <% end %>

</div>

<% if current_page?(root_path) || current_page?(homes_path) %>
  <%= render 'shared/navtabs' %>
<% end %>

app/views/shared/_navtabs.html.erb
<div class="container category-tabs">
  <ul class="">
    <li class='<%= add_active_to_classes(root_path, "active", "nav-tab-item") %>'><a href="/">For You</a></li>
    <li class='<%= add_active_to_classes(homes_path, "active", "nav-tab-item") %>'><%= link_to "Homes", homes_path %></li>
    <li class='<%= add_active_to_classes(experiences_path, "active", "nav-tab-item") %>'><%= link_to "Experiences", experiences_path %></li>
    <li class='<%= add_active_to_classes(nil, "active", "nav-tab-item") %>'><a href="#">Places</a></li>
    <li class='<%= add_active_to_classes(homes_path, "active", "nav-tab-item") %>'><%= link_to "Professional Services", services_path %></li>
  </ul>
</div>

app/views/shared/_partial_footerbox.html.erb
<footer class="footer">
  <div class="container">
    <div class="footer-box">

        <div class="row ft-widget-top">
             <div class="col-md-6">
                  <div class="ft-tagline">
                       <p>Elevate your lifestyle</p>
                       <p>Do it the <strong>GoHiSO</strong> way</p>

                  </div>
                  <div class="row">
                      <div class="col-md-6">
                           <select id="lang-selector" name="lang-selector" class="select-gh">
                                <option value="en">English</option>
                                <option value="fr">France</option>
                                <option value="in">Italiano</option>
                          </select>
                      </div>
                      <div class="col-md-6">
                           <select id="currency-selector" name="currency-selector" class="select-gh">
                                <option value="usd">USD</option>
                                <option value="eu">EURO</option>
                                <option value="jpy">YEN</option>
                          </select>
                      </div>
                  </div>

             </div>
             <div class="col-md-6">
                  <div class="ft-about">
                       <h3 class="brand-color">GOHISO</h3>
                       <p>Eu eleifend petentium incorrupte cum. Nonumy postea malorum ex pro, ne luptatum accommodare vis. Ex vim illum lorem, ad est suas mediocritatem. Duo in dolor facilisi praesent. Duo ex impetus ornatus accumsan, quem nonumes vim eu.</p>
                  </div>
             </div>
        </div>

        <div class="ft-menu">
              <h4>Questions? Contact Us.</h4>
              <div class="row ft-menu-nav">
                  <div class="col-md-3">
                       <a href="javascript:void(0)">FAQ</a>
                       <a href="javascript:void(0)">PRIVACY</a>
                  </div> 
                  <div class="col-md-3">
                       <a href="javascript:void(0)">BLOG</a>
                       <a href="javascript:void(0)">TERM OF SERVICE</a>
                  </div> 
                  <div class="col-md-3">
                       <a href="javascript:void(0)">JOB</a>
                       <a href="javascript:void(0)">HELP CENTER</a>
                  </div> 
                  <div class="col-md-3">
                       <a href="javascript:void(0)">ACCOUNT</a>
                       <a href="javascript:void(0)">COOKIE PREFERENCES</a>
                  </div>  
              </div>  

              <br class="clear" />
        </div>
        
        <div class="row">

            <div class="footer-bottom">
                <div class="ft-logo pull-left">
                    <h5 class="brand-logo">&copy; GOHISO</h5> 
                </div>
        
                <div class="ft-social pull-right">
                    <ul>
                       <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                       <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                       <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>

            </div>
            <!--/footer-bottom-->

        </div>

    </div>
    <!--/footer-box-->
  </div>
</footer>

<script type="text/javascript">

    $('select.select-gh').select2({width:200,minimumResultsForSearch:-1});
    $('b[role="presentation"]').hide();
    $('.select2-selection__arrow').append('<i class="fa fa-chevron-down"></i>');

    $('.ghs-slider').slick({
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow: 3,
        variableWidth: true,
        prevArrow: '<span class="slicknav slick-prev"><i class="fa fa-chevron-left"></span>',
        nextArrow: '<span class="slicknav slick-next"><i class="fa fa-chevron-right"></span>',
        responsive: [
        {
          breakpoint: 900,
          settings: {
            slidesToShow: 4,
            slidesToScroll: 4,
            infinite: true,
          }
        },        
        {
          breakpoint: 480,
          settings: {
            slidesToShow: 1,
            //slidesToScroll: 3,
            infinite: true,
          }
        },
      ]
    });    

    $('#ghscards-featured-loc').slick({
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow: 6,
        variableWidth: true,
        prevArrow: '<span class="slicknav slick-prev"><i class="fa fa-chevron-left"></span>',
        nextArrow: '<span class="slicknav slick-next"><i class="fa fa-chevron-right"></span>'
    });

    //--Temp fixes for select.form-control
    $( "form select" ).each(function( index ) {
        $( this ).addClass("form-control");
    });


</script>