config/routes.rb
Rails.application.routes.draw do

  get 'bookings/index'

  get 'bookings/client_bookings'

  get 'bookings/show'

  get 'bookings/edit'

  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations',
                               :sessions => 'users/sessions'
  														}

  devise_for :administrators,
             path: '',
             path_names: {sign_in: 'admin_login', sign_out: "admin_logout"},
             controllers: {sessions: "administrators/sessions"}

  resources :users, only: [:show]
  resources :rooms
  resources :photos
  resources :experiences
  resources :expphotos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :actphotos
  resources :activities

  resources :experiences do 
    resources :expreservations, only: [:create]
    resources :activities
  end

  resources :professionals, only: [:index, :show] do
    post 'submit_application', on: :member
    get 'apply', on: :collection
  end

  resources :services, only: [:index, :show] do
    post :book, on: :member
  end

  get '/my_services' => 'services#my_services'

  resources :my_services, controller: "services", only: [:new, :edit, :create, :update, :destroy]


  resources :my_bookings, controller: "bookings", only: [:index, :show, :edit]

  get '/client_bookings' => 'bookings#client_bookings'
  get '/client_bookings/:id', to: "bookings#show_client", as: "show_client_booking"

  namespace :administration do
    get "dashboard", to: "dashboard#index", as: "dashboard"
    resources :professionals, only: [:index] do
      get "for_approval", on: :collection
      patch "approve", on: :member
    end
    resources :service_categories, only: [:index, :new, :create, :edit, :update, :delete]
    resources :services, only: [:index, :show] do
      patch "status_update", on: :member      
    end
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/exp_your_itineraries' => 'expreservations#exp_your_itineraries'

  post '/exp_notify' => 'expreservations#exp_notify'
  post '/exp_your_itineraries' => 'expreservations#exp_your_itineraries'
  

  get '/search' => 'pages#search'
  get '/homes' => 'pages#homes'

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :user
  has_many :expphotos
  has_many :activities
  has_many :expreservations

  geocoded_by :city
  after_validation :geocode, if: :city_changed?

  validates :day_type, presence: true
  validates :city, presence: true
  validates :category, presence: true
  validates :language, presence: true
  validates :experience_name, presence: true, length: {maximum: 50}
  validates :experience_tagline, presence: true, length: {maximum: 500}
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  before_action :set_experience, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show, :index]

  def index
  	#@experiences = current_user.experiences
    #@users = User.where({ isFeatured: true })
    @users = User.all
    @experiences = Experience.all.take(6)
    
  end

  def show
  	@expphotos = @experience.expphotos
    @activities = @experience.activities
  end

  def new
  	@experience = current_user.experiences.build
  end

  def create
    @experience = current_user.experiences.build(experience_params)

    if @experience.save 

      if params[:images]
        params[:images].each do |image|
          @experience.expphotos.create(image: image)
        end
      end

      @expphotos = @experience.expphotos
      redirect_to edit_experience_path(@experience), notice: "Saved..."
    else
      render :new
    end
  end

  def edit
  	if current_user.id == @experience.user.id
  		@expphotos = @experience.expphotos
  	else
  		redirect_to root_path, notice: "You don't have permission."
  	end
  end

  def update
  	if @experience.update(experience_params)
  		if params[:images]
  			params[:images].each do |image|
  				@experience.expphotos.create(image: image)
  			end
  		end

  		redirect_to edit_experience_path(@experience), notice: "Updated..."

  		
  	else
  		render :edit
  	end
  end

  private
  	def set_experience
  		@experience = Experience.find(params[:id])
  	end

  	def experience_params
  		params.require(:experience).permit(:day_type, :city, :category, :language, :experience_name, :experience_tagline)
  	end

end

app/views/experiences/_activityform.html.erb
<div class="row">
	
</div>

app/views/experiences/_form.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div class="container">  
      <h1 class="brand-color">Create your Beautiful Experience</h1>
      <br />
      <br />
      <div class="row">
        <div class="col-lg-8">
				
				<%= form_for @experience, :html => {:multipart => true, class: "form-horizontal color-invert"} do |f| %>

                    <div class="form-group">
                      <label for="city" class="col-sm-4 control-label">City</label>
                      <div class="col-sm-8">
                          <%= f.select :city, [["Makati", "Makati"], ["Muntinlupa", "Muntinlupa"], ["Quezon", "Quezon"]], id: "city", prompt: "Select a city", class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="day_type" class="col-sm-4 control-label">Type</label>
                      <div class="col-sm-8">
							<%= f.select :day_type, [["Single Day", "Single Day"], ["Multiple Days", "Multiple Days"]], id: "day_type", prompt: "Select a type", class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="category" class="col-sm-4 control-label">Category</label>
                      <div class="col-sm-8">
							<%= f.select :category, [["Arts & Design", "Arts & Design"],["Fashion", "Fashion"],["Entertainment", "Entertainment"],["Sports", "Sports"],["Wellness", "Wellness"],["Nature", "Nature"],["Food & Drink", "Food & Drink"],["Lifestyle", "Lifestyle"],["History", "History"],["Music", "Music"],["Business", "Business"],["Nightlife", "Nightlife"]], id: "category", prompt: "Select a category", class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="experience_name" class="col-sm-4 control-label">Title of Experience</label>
                      <div class="col-sm-8">
							<%= f.text_field :experience_name, placeholder: "Name the experience", class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="experience_tagline" class="col-sm-4 control-label">Add a tagline</label>
                      <div class="col-sm-8">
							<%= f.text_field :experience_tagline, placeholder: "Write the tagline here", class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="language" class="col-sm-4 control-label">Language</label>
                      <div class="col-sm-8">
							<%= f.select :language, [["English", "English"], ["Filipino", "Filipino"]], id: "language", prompt: "Select a language", class: "form-control" %>
                      </div>
                    </div>

                    <div class="form-group">
	                      <div class="col-sm-offset-4 col-sm-8">
								<span class="btn btn-default btn-file">
									<i class="fa fa-cloud-upload fa-lg"></i> Upload Photos
									<%= file_field_tag "images[]", type: :file, multiple: true %>
								</span>
	                      </div>
                    </div>


					 <div class="form-group">
					    <div class="col-sm-offset-4 col-sm-8">
					       <div id="expphotos"><%= render 'expphotos/list' %></div>
					    </div>
					 </div>

					 <div class="form-group actions">
					    <div class="col-sm-offset-4 col-sm-8">
					       <%= f.submit "Save", class: "btn btn-primary" %>
					    </div>
					 </div>


                <% end %>   

        </div>
        <!--/col-lg-8-->
        
        <!-- create activities -->
        <div class="col-lg-8">
          <h2>Create Activities</h2>
          
          <%= render 'activityform' %>
        </div>

      </div><!--/row-->
        
</div>        

app/views/experiences/_sidebar.html.erb
<ul class="sidebar-list">
	<li class="sidebar-item"><i class="fa fa-list-alt"></i>&nbsp;&nbsp;<%= link_to "Your Listing", your_listings_path, class: "sidebar-link" %></li>
	<li class="sidebar-item"><i class="fa fa-calendar"></i>&nbsp;&nbsp;<%= link_to "Your Reservations", experiences_path, class: "sidebar-link" %></li>
	<li class="sidebar-item"><i class="fa fa-history"></i>&nbsp;&nbsp;<%= link_to "Your Itineraries", your_itineraries_path, class: "sidebar-link active" %></li>
</ul>

app/views/experiences/create.html.erb
<h1>Experiences#create</h1>
<p>Find me in app/views/experiences/create.html.erb</p>

app/views/experiences/edit.html.erb
<%= stylesheet_link_tag params[:controller] %>
<%= render 'form' %>

app/views/experiences/guestrequire.html.erb
<div class="container">
	<h1>Review guest requirements</h1>


	<h2>Age</h2>
	<p>All guests must be at least 18 years old and children can't come along</p>
	<hr>
	<h2>Government ID</h2>
	<p>You'll need to take a selfie and match it to the photo on your ID. This is so GoHiSo can confirm who's actually going on the experience. You'll have to do this once.</p>
</div>

app/views/experiences/guests.html.erb
<div class="container">
	<h1>Who's coming?</h1>

	<div class="row">
		<div class="col-md-8"><%= current_user.fullname %></div>
		<div class="col-md-4"><%= image_tag avatar_url(current_user), class: "item-avatar" %></div>
	</div>
	
</div>

app/views/experiences/index.html.erb
<%= stylesheet_link_tag params[:controller] %>
<div class="hero-banner-img-wrap" style="background-image: url('<%= image_url('gohiso-party.jpg') %>')">
    <div class="container">
        <div class="row">
              <div class="hero-box">
                  <div class="hero-quicksearch">
                      <h1 class="brand-color">GoHiSo Experience</h1>
                      <h2>Elevate your lifestyle</h2>
                  </div>
              </div>
        </div>
    </div>
</div>


<!-- EXPERIENCES -->
<% if @experiences %>
<div class="container exp-header">  
  <h2>Latest Experiences</h2>
  <p>Experience the latest, wildly-booked activities of GoHiSo.</p>
</div>

<div class="container grid-cards 2cols">
    <div class="row">
          
            <% @experiences.each do |experience| %>
                <% @expphoto = experience.expphotos.take(1) %>
                <div class="col-sm-6">
                  <a href="experiences/<%= experience.id %>">
                    <div class="item">
                      <% if @expphoto %>
                        
                        <img src="<%= image_url(@expphoto[0].image_file_name) %>" />
                      <% else %>
                        <img src="<%= image_url('whale.jpg') %>" />

                      <% end %>
                      <span class="item-name"><%= experience.experience_name %></span>
                      <span class="desc">
                        <%= experience.experience_tagline %>
                      </span>
                    </div>  
                  </a>
              </div>
            <% end %>
          
    </div>  
</div>
<% end %>

<!-- PROFESSIONALS -->
<div class="container exp-header">  
  <h2>Connect with local Professionals</h2>
  <p>Learn from local legends, like surf pros, up-and-coming artists, master chefs, and nonprofit founders.</p>
</div>

<div class="container grid-cards 2cols">
    <div class="row">
          <% if @users %>
            <% @users.each do |user| %>
                <% if user.isFeatured == true %>
               <div class="col-sm-6">
                <a href="users/<%= user.id %>">
                  <div class="item">
                    <img src="<%= image_url(user.image) %>" />
                    <span class="desc"><%= user.description %></span>
                  </div> 
                </a> 
              </div>
              <% end %>
            <% end %>
          <% end %>
    </div>  
</div>


<br />
<br />
<br class="clear" />

<div class="be-host-box gradient-brand">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Want to host an experience?</h2>
                <p>See what it takes to host an experience and show travelers your city.</p>
            </div>
            <div class="col-md-6">
                <div class="actionBtn">
                  <a href="#" class="btn btn-rounded">Become a Host</a>
                </div>
            </div>  
        </div>    
    </div>    
</div>

app/views/experiences/index2.html.erb
<div class="hero-banner-img-wrap" style="background-image: url('<%= image_url('gohiso-party.jpg') %>')">
    <div class="container">
        <div class="row">
              <div class="hero-box">
                  <div class="hero-quicksearch">
                      <h1 class="brand-color">GoHiSo Experience</h1>
                      <h2>Elevate your lifestyle</h2>
                  </div>
              </div>
        </div>
    </div>
</div>

<div class="container exp-header">  
  <h2>Connect with local Professionals</h2>
  <p>Learn from local legends, like surf pros, up-and-coming artists, master chefs, and nonprofit founders.</p>
</div>

<div class="container grid-cards 2cols">
    <div class="row">
          <div class="col-sm-6">
              <div class="item">
                <img src="<%= image_url('cards_-45.png') %>" />
                <span class="desc">With more than 5 million followers on Instagram, 17-year-old Bretman Rock has taken the Internet by storm...</span>
              </div>  
          </div>
          <div class="col-sm-6">
              <div class="item">
                <img src="<%= image_url('cards_-46.png') %>" />
                <span class="desc">YouTuber who is known for maintaining his health-centric, eponymous channel, which he launched in June 2012...</span>
              </div>  
          </div>
          <div class="col-sm-6">
              <div class="item">
                <img src="<%= image_url('cards_-47.png') %>" />
                <span class="desc">a Filipino racing driver, who raced for Status Grand Prix in the 2012 GP3 Series and currently driving for Lotus F1 Team Juniors...</span>
              </div>  
          </div>
          <div class="col-sm-6">
              <div class="item">
                <img src="<%= image_url('cards_-48.png') %>" />
                <span class="desc">a Filipino-American actress and model. She started in a range of television series and films, including Wansapanataym..</span>
              </div>  
          </div>

          <div class="col-sm-6">
              <div class="item">
                <img src="<%= image_url('cards_-50.png') %>" />
                <span class="desc">a Filipina actress. Her first major role was as supporting cast member on the ABS-CBN remake of Mula Sa Puso..</span>
              </div>  
          </div>

          <div class="col-sm-6">
              <div class="item">
                <img src="<%= image_url('cards_-49.png') %>" />
                <span class="desc">a Filipino - Canadian singer. He made his first television appearance at the age of ten when he joined YTV's reality television The Next Star in 2012..</span>
              </div>  
          </div>

    </div>  
</div>


<br />
<br />
<br class="clear" />

<div class="be-host-box gradient-brand">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Want to host an experience?</h2>
                <p>See what it takes to host an experience and show travelers your city.</p>
            </div>
            <div class="col-md-6">
                <div class="actionBtn">
                  <a href="#" class="btn btn-rounded">Become a Host</a>
                </div>
            </div>  
        </div>    
    </div>    
</div>

app/views/experiences/new.html.erb
<%= render 'form' %>

app/views/experiences/show.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div class="container exp-page">
    <div class="row">

      <div class="col-lg-7 col-md-6 col-sm-12">
        <div class="content-details">
         
         <div class="tagline-details">
             <h2 class="h2"><%= @experience.experience_name %></h2>
             <p><strong><%= @experience.city %></strong> <%= @experience.experience_tagline %></p>
         </div>

         <div class="boxed-details">
            <p><%= @experience.category %></p>
            <p>Hosted by <%= link_to @experience.user.fullname, @experience.user %></p>
            <p>
            <% if current_user %>
            <%= link_to "Contact Host", conversations_path(sender_id: current_user.id, recipient_id: @experience.user.id), method: 'post' %>
            <% else %>
            <a href="#">Contact Host</a>
            <% end %>
            </p>
            
            <ul class="exp-specs-details">
              <li><i class="fa fa-calendar"></i><%= @experience.day_type %></li>
              <li><i class="fa fa-clock-o"></i>  11.5 hours total</li>
              <li><i class="fa fa-cutlery"></i>  2 meals, drinks, equipment and transportation</li>
              <li><i class="fa fa-comments"></i>  Offered in <%= @experience.language %></li>
            </ul>
         </div>

        
          <% if @activities %>
            <div class="activities-section">
              <h2>Activities</h2>

              <% @activities.each do |activity| %>

                <h3>Day 1:</h3>
                <h4><%= activity.title %></h4>
                <p class="subtitle"><%= activity.subtitle %></p>
                <h4>What to do?</h4>
                <p><%= activity.what_to_do %></p>
                <h4>Where we'll be?</h4>
                <p><%= activity.where_well_be %></p>
                <% if activity.notes %>
                  <h4>Additional notes</h4>
                  <p><%= activity.notes %></p>
                <% end %>
                <h4>Location</h4>
                <p><%= activity.location_name %> <%= activity.street_address %> <%= activity.building %> <%= activity.city %> <%= activity.state %> <%= activity.zipcode %> </p>
              <% end %>
            </div>
          <% end %>
        
        <br>
        <hr>

        <!-- Google Map -->
        <div class="googlemap">
          <div class="col-md-12">
            <div id="map"></div>
            <style>
              #map {
                width: 100%;
                height: 400px;
              }
            </style>
            <script>
              function initMap() {
                var uluru = {lat: <%= @experience.latitude %>, lng: <%= @experience.longitude %>};
                var map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 14,
                  center: uluru
                });
                var marker = new google.maps.Marker({
                  position: uluru,
                  map: map
                });
              }
            </script>
            <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrkinOiy-78rJq1uLTy-jkAW1aHbfFYCo&callback=initMap">
            </script>
          </div>
        </div>

        <br>
        <hr>

         <div class="about-details">
              <br />

              <span class="block"><strong>About your host, <%= @experience.user.fullname %></strong></span>
              <p><%= @experience.user.description %></p>
              <br />
         </div>


        </div>
      </div>
      <div class="col-lg-5 col-md-6 col-sm-12">

        <div class="exp-card-container">
             <div class="exp-card" data-spy="affix" data-offset-top="90" data-offset-bottom="530">
  			<% @expphotos.each do |expphoto| %>
  				
          <img src="<%= image_url(expphoto.image_file_name) %>" class="experience-image"/>
  			<% end %>
             	<!--
               <img src="https://a0.muscache.com/im/pictures/c380debc-e608-4b0f-9df1-73a9474ccd5a.jpg?aki_policy=xl_poster" />
               -->
            </div>
            <br>
        <div class="price-text"><%=  @experience.price_currency %><%=  @experience.price %></div>
  		  <button class="btn btn-primary" data-toggle="modal" data-target="#schedule-modal">See Dates</button>
        </div>
          
      </div>  




    </div>
    <!--/row-->
</div>




    <div class="modal fade" id="schedule-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Modal Header</h4>
              </div>
                <div class="modal-body">

                  <%= form_for([@experience, @experience.expreservations.new]) do |f| %>
                  <div class="row">
                    
                      <div class="col-md-9"><%= @experience.created_at.to_formatted_s(:long_ordinal)%></div>
                      <div class="col-md-3">
                        <%= f.hidden_field :price_currency, value: @experience.price_currency %>
                        <%= f.hidden_field :price, value: @experience.price %>
                        <%= f.hidden_field :total, value: @experience.price %>
                        <%= f.hidden_field :experience_id, value: @experience.id %>
                        <%= f.submit "Book", class: "btn btn-primary" %>
                      </div>
                  </div>
                  <hr>
                  <% end %>
                
                </div>


            </div>
        </div>
    </div>







<!--
	<div class="row">
		<% @expphotos.each do |expphoto| %>
			<%= image_tag expphoto.image.url(), class: "experience-image" %>
		<% end %>
	</div>
-->

app/views/experiences/update.html.erb
<h1>Experiences#update</h1>
<p>Find me in app/views/experiences/update.html.erb</p>

app/views/experiences/your_listings.html.erb
<div class="container myDashboard"> 

    <div id="myDashboard" class="row">

		<div class="col-md-3">
			<%= render 'sidebar' %>
		</div>

		<div class="col-md-9">
              <h3 class="h3">Your Listings</h3>
              <div class="myItineryList">
				<% if current_user.experiences.empty? == false %>
	              	<% current_user.experiences.each do |experience| %>

	                    <div class="item">
	                           <%= link_to experience_path(experience) do %>
	                           <div class="itr_img" style="background-image: url('<%= experience.expphotos[0].image.url(:medium) %>');">
	                           </div>
	                           <% end %>

	                           <!--# Dyanamic Avatar -->
	                           <!--

	                           Hi Ernest, can you fix the "avatar_url(...)"? i'm not able to get the full path of the image. thanks!
	-->
	                           <%= link_to user_path(experience.user_id) do %>
	                             <%= image_tag avatar_url(experience.user), class: "item-avatar" %>
	                           <% end %>
	                           

	                           <!--# TEMPORARY Static Avatar 
								<div class="item-avatar" style="background-image: url('http://ec2-34-208-88-113.us-west-2.compute.amazonaws.com:3002/assets/cards_-45-430e9ef4295121ddded70f1e7e9cf75965d405239e42b9122bebe43dd843ef04.png')"></div>
							-->

	                          <div class="itr_details">
	                                <div class="item-header">
	                                     <h4> <%= link_to experience_path(experience) do %><%= experience.experience_name %><% end %></h4>
	                                </div>
	                                <p>May 20-22, 2017  &bull; <%= experience.city %>  &bull; Php <%= experience.price %></p>
	                                <br />
	                                <div class="link_options">
	                                  <p> <a href="#"><i class="fa fa-credit-card"></i> &nbsp;View Receipt</a></p>
	                                  <p> <a href="#"><i class="fa fa-money"></i> &nbsp;Send or Request Money</a></p>
	                                  <p> <a href="#"><i class="fa fa-star"></i> &nbsp;Read your Review</a></p>
	                                </div>
	                          </div> 
	                    </div>

	                <% end %>
	            <% else %>
					<p>You currently don't have any listings.</p>
					<p>Click here to host an experience!</p>
					<%= link_to "Host an experience", new_experience_path, class: "btn btn-primary" %>
	            <% end %>

              </div>
              <!--/myItineryList -->


		</div>

	</div>

</div>
<!--/container -->