config/routes.rb
Rails.application.routes.draw do

  get 'bookings/index'

  get 'bookings/client_bookings'

  get 'bookings/show'

  get 'bookings/edit'

  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations',
                               :sessions => 'users/sessions'
  														}

  devise_for :administrators,
             path: '',
             path_names: {sign_in: 'admin_login', sign_out: "admin_logout"},
             controllers: {sessions: "administrators/sessions"}

  resources :users, only: [:show]
  resources :rooms
  resources :photos
  resources :experiences
  resources :expphotos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :actphotos
  resources :activities

  resources :experiences do 
    resources :expreservations, only: [:create]
    resources :activities
  end

  resources :professionals, only: [:index, :show] do
    post 'submit_application', on: :member
    get 'apply', on: :collection
  end

  resources :services, only: [:index, :show] do
    post :book, on: :member
  end

  get '/my_services' => 'services#my_services'

  resources :my_services, controller: "services", only: [:new, :edit, :create, :update, :destroy]


  resources :my_bookings, controller: "bookings", only: [:index, :show, :edit]

  get '/client_bookings' => 'bookings#client_bookings'
  get '/client_bookings/:id', to: "bookings#show_client", as: "show_client_booking"

  namespace :administration do
    get "dashboard", to: "dashboard#index", as: "dashboard"
    resources :professionals, only: [:index] do
      get "for_approval", on: :collection
      patch "approve", on: :member
    end
    resources :service_categories, only: [:index, :new, :create, :edit, :update, :delete]
    resources :services, only: [:index, :show] do
      patch "status_update", on: :member      
    end
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/exp_your_itineraries' => 'expreservations#exp_your_itineraries'

  post '/exp_notify' => 'expreservations#exp_notify'
  post '/exp_your_itineraries' => 'expreservations#exp_your_itineraries'
  

  get '/search' => 'pages#search'
  get '/homes' => 'pages#homes'

end

app/controllers/administration/dashboard_controller.rb
class Administration::DashboardController < AdministrationController
  def index
  end
end

app/controllers/administration/professionals_controller.rb
class Administration::ProfessionalsController < AdministrationController
  def index
  end

  def for_approval
  	@pending_professionals = User.for_approval
  end

  def approve
  	@user = User.find(params[:id])
  	@user.update_attributes(user_level: 1)
  	redirect_to for_approval_administration_professionals_path, notice: "Yup, that guy is now a professional."
  end
end

app/controllers/administration/service_categories_controller.rb
class Administration::ServiceCategoriesController < AdministrationController
	before_action :set_service_category, only: [:edit, :update, :destroy]
  def index
  	@service_categories = Service::Category.all
  end

  def new
  	@service_category = Service::Category.new
  	@service_category.questions.build.answers.build
  end

  def create
  	@service_category = Service::Category.new(service_params)

  	if @service_category.save
  		redirect_to edit_administration_service_category_path(@service_category), notice: "Successfully created #{@service_category.title}."
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if @service_category.update_attributes(service_params)
  		redirect_to edit_administration_service_category_path(@service_category), notice: "Successfully updated #{@service_category.title}."
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@service_category.destroy
  	redirect_to administration_service_categories_path, notice: "Successfully deleted #{@service_category.title}."
  end

  private
  def set_service_category
  	@service_category = Service::Category.find_by_slug(params[:id])
  end

  def service_params
  	params.require(:service_category).permit(
  		:title, :description, :slug, :minimum_rate, :maximum_rate, :commission_percentage,
  		questions_attributes: [
  			:id, :_destroy, :label, :question,
  			answers_attributes: [
  				:id, :_destroy, :answer
  			]
  		]
  	)
  end
end

app/controllers/administration/services_controller.rb
class Administration::ServicesController < AdministrationController
	before_action :set_service, only: [:status_update, :show]

  def index
  	@services = Service::Service.all
  end

  def status_update
  	if @service.update_attributes(status_update_params)
  		redirect_to administration_services_path, notice: "Successfully updated status of service."
  	else
  		render "index"
  	end
  end

  def show

  end

  private
  def set_service
  	@service = Service::Service.find(params[:id])
  end

  def status_update_params
  	params.require(:service_service).permit(:status)
  end
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
	before_action :prevent_user
	before_action :prevent_guest

	layout 'administration'

	private
	def prevent_guest
		if !administrator_signed_in?
			redirect_to root_path, notice: "You must be lost hooman."
		end
	end
end

app/helpers/administration/dashboard_helper.rb
module Administration::DashboardHelper
end

app/helpers/administration/professionals_helper.rb
module Administration::ProfessionalsHelper
end

app/helpers/administration/service_categories_helper.rb
module Administration::ServiceCategoriesHelper
end

app/helpers/administration/services_helper.rb
module Administration::ServicesHelper
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/views/administration/service_categories/_answer_fields.html.erb
<div class="row nested-fields">
	<div class="col-sm-9 col-md-10">
		<%= f.input :answer, as: :string %>	
	</div>
	<div class="col-sm-3 col-md-2">
		<%= link_to_remove_association "Remove Ans", f, class: "btn btn-danger btn-sm" %>
	</div>
</div>

app/views/administration/service_categories/_form.html.erb
<%= simple_form_for @service_category, url: url, method: method do |f| %>
	<div class="row">
		<div class="col-sm-12 col-md-6">
			<%= f.input :title, as: :string %>
		</div>
		<div class="col-sm-12 col-md-6">
			<%= f.input :slug %>
			<p><i>Slug is not required, it is automatically generated from the title if none is provided. this is the identifier of this category.</i></p>
		</div>
	</div>
	<%= f.input :description %>
	<div class="row">
		<div class="col-sm-4">
			<%= f.input :minimum_rate %>
		</div>
		<div class="col-sm-4">
			<%= f.input :maximum_rate %>
		</div>
		<div class="col-sm-4">
			<%= f.input :commission_percentage %>
		</div>
	</div>

	<h3>Questions</h3>
	<div id="questions">
		<%= f.simple_fields_for :questions do |q| %>
			<%= render 'question_fields', f: q %>
		<% end %>
		<div class="links">
			<%= link_to_add_association 'Add Question', f, :questions, class: "btn btn-primary" %>
		</div>
	</div>
	<%= f.submit class: "btn btn-lg btn-success" %>
<% end %>

app/views/administration/service_categories/_question_fields.html.erb
<div class="nested-fields">
	<%= f.input :label %>
	<p><i>The label is displayed, in place of the question, in the booking once a user answers the question.</i></p>
	<%= f.input :question %>
	<h4>Answers</h4>
	<div id="answers">
		<%= f.simple_fields_for :answers do |answer| %>
			<%= render "answer_fields", f: answer %>
		<% end %>
		<div class="links">
			<%= link_to_add_association "Add Answers", f, :answers, class: "btn btn-warning" %>
		</div>
	</div>
	<%= link_to_remove_association "Remove Question", f, class: "btn btn-danger" %>
	<hr>
</div>

app/views/administration/service_categories/edit.html.erb
<%= render "form", url: administration_service_category_path(@service_category), method: :patch %>

app/views/administration/service_categories/index.html.erb
<%= link_to "New Category", new_administration_service_category_path, class: "btn btn-lg btn-primary" %>

<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Slug</th>
			<th>Services</th>
			<th>Min Rate</th>
			<th>Max Rate</th>
			<th>Comm %</th>
			<th>Questions</th>
			<th colspan="1"></th>
		</tr>
	</thead>
	<tbody>
		<% @service_categories.each do |category| %>
			<tr>
				<td><%= category.id %></td>
				<td><%= category.title %></td>
				<td><%= category.slug %></td>
				<td><%= category.services.size %></td>
				<td><%= number_to_currency category.minimum_rate %></td>
				<td><%= number_to_currency category.maximum_rate %></td>
				<td><%= category.commission_percentage %>%</td>
				<td><%= category.questions.size %></td>
				<td>
					<%= link_to "Edit", edit_administration_service_category_path(category), class: "btn btn-sm btn-warning" %>
					<%= link_to "Delete", administration_service_category_path(category), method: :delete, data: {confirm: "Are you sure you want to delete this category?"}, class: "btn btn-sm btn-danger" %>
					</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/administration/service_categories/new.html.erb
<h1>New Category</h1>

<%= render "form", url: administration_service_categories_path, method: :post %>

app/views/administration/service_categories/show.html.erb
<h1>Administration::ServiceCategories#show</h1>
<p>Find me in app/views/administration/service_categories/show.html.erb</p>